import subprocess
import re
import time
import sys
import os
from datetime import datetime, timedelta

def convert_to_netscape(input_filename, output_filename="netscape-cookies.txt"):
    """
    将 Chrome 复制的 cookies 文件转换为 Netscape 格式并保存到指定文件。
    输入文件每行格式：name  value  domain  path  expiration  size  httpOnly
    输出 Netscape 格式：domain  flag  path  secure  expiry  name  value
    """
    try:
        if not os.path.exists(input_filename):
            print(f"错误：文件 {input_filename} 不存在", file=sys.stderr)
            sys.exit(1)

        with open(input_filename, 'r', encoding='utf-8') as f:
            content = f.read()
            cookies = content.split('\n')

        # 打开输出文件
        with open(output_filename, 'w', encoding='utf-8') as f:
            # 输出 Netscape 文件头
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by convert_cookies.py\n\n")

            for cookie in cookies:
                # 跳过空行
                if not cookie.strip():
                    continue

                # 分割 cookie 字段
                fields = cookie.split('\t')
                if len(fields) < 5:
                    continue  # 跳过格式不正确的行
                name, value, domain, path, expiration = fields[:5]
                httpOnly = fields[6] if len(fields) > 6 else 'FALSE'

                if not name:
                    continue

                # 处理 domain：如果不以 '.' 开头，添加 '.'
                if domain and domain[0] != '.':
                    domain = '.' + domain

                # 处理 httpOnly
                httpOnly = 'TRUE' if httpOnly == '✓' else 'FALSE'

                # 处理 expiration
                if expiration.lower() == 'session':
                    expiration = datetime.now() + timedelta(days=1)
                try:
                    expiration = int(datetime.fromisoformat(expiration.replace('Z', '+00:00')).timestamp())
                except ValueError:
                    # 如果日期格式无效，设为会话 cookie
                    expiration = 0

                # 写入 Netscape 格式的一行
                f.write(f"{domain}\tTRUE\t{path}\t{httpOnly}\t{expiration}\t{name}\t{value}\n")

        print(f"已成功将 cookies 转换为 Netscape 格式，保存到 {output_filename}")

    except Exception as e:
        print(f"转换失败：{e}", file=sys.stderr)
        sys.exit(1)
        
def convert_cookies_to_netscape(cookies: str, output_filename="netscape-cookies.txt"):
    """
    将 Chrome 复制的 cookies 转换为 Netscape 格式并保存到指定文件。
    输入文件每行格式：name  value  domain  path  expiration  size  httpOnly
    输出 Netscape 格式：domain  flag  path  secure  expiry  name  value
    """
    try:

        # 打开输出文件
        with open(output_filename, 'w', encoding='utf-8') as f:
            # 输出 Netscape 文件头
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by convert_cookies.py\n\n")

            for cookie in cookies:
                # 跳过空行
                if not cookie.strip():
                    continue

                # 分割 cookie 字段
                fields = cookie.split('\t')
                if len(fields) < 5:
                    continue  # 跳过格式不正确的行
                name, value, domain, path, expiration = fields[:5]
                httpOnly = fields[6] if len(fields) > 6 else 'FALSE'

                if not name:
                    continue

                # 处理 domain：如果不以 '.' 开头，添加 '.'
                if domain and domain[0] != '.':
                    domain = '.' + domain

                # 处理 httpOnly
                httpOnly = 'TRUE' if httpOnly == '✓' else 'FALSE'

                # 处理 expiration
                if expiration.lower() == 'session':
                    expiration = datetime.now() + timedelta(days=1)
                try:
                    expiration = int(datetime.fromisoformat(expiration.replace('Z', '+00:00')).timestamp())
                except ValueError:
                    # 如果日期格式无效，设为会话 cookie
                    expiration = 0

                # 写入 Netscape 格式的一行
                f.write(f"{domain}\tTRUE\t{path}\t{httpOnly}\t{expiration}\t{name}\t{value}\n")

        print(f"已成功将 cookies 转换为 Netscape 格式，保存到 {output_filename}")

    except Exception as e:
        print(f"转换失败：{e}", file=sys.stderr)
        sys.exit(1)

